# Use Ctrl + Shift + square brackets to change windows
bind-key -n C-S-[ previous-window
bind-key -n C-S-] next-window

# Have windows count up from 1, not 0, and automatically renumber 
# when a window is closed--makes it easier to use tmux-key + # keys
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
